#!/bin/bash
#script name:call_js-beautifier

PROJECT_DIR="/Users/sphing_phong/Documents/zom/AutoDash/AutoDashMobile"
temp_file="/Users/sphing_phong/Documents/zom/AutoDash/AutoDashMobile/temp_file"
for i in ${PROJECT_DIR}/www/app/*.js
do
python ${PROJECT_DIR}/js-beatifier $i > $temp_file
echo ${PROJECT_DIR}/ >> ~/Desktop/log.txt
mv $temp_file $i
done
